[package]
name = "hello_blockchain"
version = "1.0.0"
authors = []

[addresses]
hello_blockchain = "_"

[dev-addresses]

[dependencies.AptosFramework]

local = "/Users/siddharthmanjul/AptosCore/aptos-core-main/aptos-move/framework/aptos-framework"
rev="devnet" 

[dependencies]
MoveStdlib = { local = "/Users/siddharthmanjul/AptosCore/aptos-core-main/aptos-move/framework/move-stdlib", rev = "devnet", addr_subst = { "std" = "0x1" } }

[dev-dependencies]
